#!/usr/bin/env python3
"""Estimate contamination-free OBS baseline prognosis with an RSF.

The development train and validation cohorts are pooled.  Only patients who
actually received observation (OBS) are used to tune or fit a prognostic
model.  In the default ``nested`` mode, every OBS prediction is generated by
an outer-fold model whose Optuna search and model fit both excluded that
patient.  A separate Optuna study on all OBS patients selects the parameters
for a final full-OBS model, which is used only to predict the ACT patients.

The output table compares predicted 60-month OBS RMST between patients whose
observed treatment was aligned versus discordant with a treatment-policy
recommendation.  With no arguments, those groups are generated using honest
development predictions from a newly tuned and fitted RSF T-learner. Prior
T-learner performance is used only to choose plausible Optuna search bounds;
no fitted model, selected parameters, or frozen recommendation is reused. An
optional patient-level CSV containing either ``recommendation`` or
``alignment`` can override the default by setting ``ALIGNMENT_FILE`` below.

Example
-------
    /Users/owensun/miniconda3/bin/python \
      test_for_hte/obs_rsf_baseline_prognosis.py

If configured, the alignment CSV must contain the patient identifier
(``patient_id`` by default) plus one of:

* ``recommendation``: OBS/ACT or 0/1; alignment is calculated against actual
  treatment.
* ``alignment``: aligned/discordant or a boolean/0/1 value.

The 18 clinical features are prespecified. If ``GENE_LIST`` is set, that list
must also be prespecified or selected without using the assessed patients'
outcomes; this script intentionally does not pretend that an externally
outcome-selected gene list is made honest by downstream folds.

Set ``SELECTION_MODE = "global"`` for the conventional, faster workflow in
which one all-OBS Optuna study supplies the parameters for the outer-fold
models. Its model fits still exclude each held-out patient, but the patient's
outcome participates in global hyperparameter selection; the default
``"nested"`` mode avoids that subtler source of contamination.
"""

from __future__ import annotations

import json
import math
import os
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

os.environ.setdefault(
    "MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "autosota-matplotlib")
)

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import optuna
import pandas as pd
from optuna.pruners import MedianPruner
from optuna.samplers import TPESampler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import StratifiedKFold
from sksurv.ensemble import RandomSurvivalForest
from sksurv.metrics import concordance_index_censored
from sksurv.util import Surv


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent

ID = "patient_id"
SOURCE_ID = "Unnamed: 0"
TREATMENT = "Adjuvant Chemo"
TIME = "OS_MONTHS"
EVENT = "OS_STATUS"

# ---------------------------------------------------------------------------
# User-editable configuration
# ---------------------------------------------------------------------------
TRAIN_CSV = REPO_ROOT / "affyfRMATrain.csv"
VALIDATION_CSV = REPO_ROOT / "affyfRMAValidation.csv"
OUTPUT_DIR = HERE / "results" / "obs_rsf_baseline_prognosis"

# Leave as None to train a new cross-fitted T-learner for alignment. To use
# existing policy labels, set this to a CSV with patient_id plus alignment or
# recommendation.
ALIGNMENT_FILE: Path | None = None
ALIGNMENT_ID_COLUMN = ID
ALIGNMENT_COLUMN = "alignment"
RECOMMENDATION_COLUMN = "recommendation"

# Optional prespecified gene list. None means clinical covariates only.
GENE_LIST: Path | None = None
GENE_COLUMN = "Gene"
MAX_GENES: int | None = None

TABLE_SPLIT = "all"  # "all", "train", or "validation"
OUTER_FOLDS = 5
INNER_FOLDS = 3
OUTER_TRIALS = 20
FINAL_TRIALS = 30
POLICY_TRIALS = 20
SELECTION_MODE = "nested"  # "nested" or "global"
TAU = 60.0
SEED = 20260910
N_JOBS = -1
BATCH_SIZE = 256
SMOKE = False

# Historically strong T-learner settings define these search bounds only.
# Optuna still selects every parameter anew in every study.
TREES_LOW = 600
TREES_HIGH = 1000
TREES_STEP = 100
BASELINE_LEAF_LOW = 5
BASELINE_LEAF_HIGH = 18
BASELINE_DEPTH_CHOICES: tuple[int | None, ...] = (7, 8, 9, 10, 11)
BASELINE_MAX_FEATURES_LOW = 0.60
BASELINE_MAX_FEATURES_HIGH = 1.0
POLICY_OBS_LEAF_BOUNDS = (5, 16)
POLICY_OBS_DEPTH_CHOICES = (7, 8, 9, 10, 11)
POLICY_ACT_LEAF_BOUNDS = (8, 20)
POLICY_ACT_DEPTH_CHOICES = (5, 6, 7, 8, 9)
POLICY_MAX_FEATURES_BOUNDS = (0.60, 1.0)

# Smoke mode overrides only computational size, not data or estimands.
SMOKE_FOLDS = 2
SMOKE_TRIALS = 2
SMOKE_TREE_BOUNDS = (30, 60, 30)

# Pretreatment variables used by the repository's RSF T-learner.  Treatment
# is deliberately absent: this model estimates prognosis under OBS only.
CLINICAL_FEATURES = [
    "Age",
    "IS_MALE",
    "Stage_IA",
    "Stage_IB",
    "Stage_II",
    "Stage_III",
    "Histology_Adenocarcinoma",
    "Histology_Adenosquamous Carcinoma",
    "Histology_Large Cell Carcinoma",
    "Histology_Squamous Cell Carcinoma",
    "Race_African American",
    "Race_Asian",
    "Race_Caucasian",
    "Race_Native Hawaiian or Other Pacific Islander",
    "Race_Unknown",
    "Smoked?_No",
    "Smoked?_Unknown",
    "Smoked?_Yes",
]


@dataclass(frozen=True)
class SearchSettings:
    folds: int
    trials: int
    seed: int
    n_jobs: int
    trees_low: int = TREES_LOW
    trees_high: int = TREES_HIGH
    trees_step: int = TREES_STEP
    leaf_low: int = BASELINE_LEAF_LOW
    leaf_high: int = BASELINE_LEAF_HIGH
    depth_choices: tuple[int | None, ...] = BASELINE_DEPTH_CHOICES
    max_features_low: float = BASELINE_MAX_FEATURES_LOW
    max_features_high: float = BASELINE_MAX_FEATURES_HIGH


def _assert_development_path(path: Path) -> None:
    """Prevent accidental use of the sealed test cohort."""
    if "test" in path.name.lower():
        raise ValueError(f"Test data are not allowed in this workflow: {path}")


def _map_treatment(values: pd.Series) -> pd.Series:
    mapped = values.map({"OBS": 0, "ACT": 1, "obs": 0, "act": 1})
    mapped = mapped.where(mapped.notna(), values)
    result = pd.to_numeric(mapped, errors="raise").astype(int)
    if not set(result.unique()).issubset({0, 1}):
        raise ValueError(f"{TREATMENT} must contain only OBS/ACT or 0/1")
    return result


def _read_gene_list(path: Path | None, column: str, max_genes: int | None) -> list[str]:
    if path is None:
        return []
    genes_frame = pd.read_csv(path)
    if column not in genes_frame:
        raise ValueError(f"Gene-list file has no {column!r} column: {path}")
    excluded = {SOURCE_ID, ID, TREATMENT, TIME, EVENT, *CLINICAL_FEATURES}
    genes = [
        gene
        for gene in genes_frame[column].dropna().astype(str).drop_duplicates().tolist()
        if gene not in excluded
    ]
    if max_genes is not None:
        genes = genes[: int(max_genes)]
    if not genes:
        raise ValueError(f"No genes were read from {path}")
    return genes


def load_development(
    train_path: Path,
    validation_path: Path,
    gene_list_path: Path | None,
    gene_column: str,
    max_genes: int | None,
) -> tuple[pd.DataFrame, list[str]]:
    """Load row-aligned development data without ever opening test data."""
    _assert_development_path(train_path)
    _assert_development_path(validation_path)
    genes = _read_gene_list(gene_list_path, gene_column, max_genes)
    features = CLINICAL_FEATURES + genes
    required = [SOURCE_ID, TREATMENT, TIME, EVENT] + features

    frames: list[pd.DataFrame] = []
    for split, path in (("train", train_path), ("validation", validation_path)):
        header = pd.read_csv(path, nrows=0).columns.tolist()
        missing = [column for column in required if column not in header]
        if missing:
            raise ValueError(f"{path.name} is missing columns: {missing}")
        frame = pd.read_csv(path, usecols=required)
        frame = frame.rename(columns={SOURCE_ID: ID})
        frame.insert(1, "split", split)
        frames.append(frame)

    development = pd.concat(frames, ignore_index=True)
    if development[ID].isna().any() or development[ID].duplicated().any():
        raise ValueError("Patient identifiers must be nonmissing and unique across splits")
    development[ID] = development[ID].astype(str)
    development[TREATMENT] = _map_treatment(development[TREATMENT])
    development[EVENT] = pd.to_numeric(development[EVENT], errors="raise").astype(int)
    development[TIME] = pd.to_numeric(development[TIME], errors="raise").astype(float)
    if not set(development[EVENT].unique()).issubset({0, 1}):
        raise ValueError(f"{EVENT} must be binary")
    if (development[TIME] <= 0).any():
        raise ValueError(f"{TIME} must be positive")
    for feature in features:
        development[feature] = pd.to_numeric(development[feature], errors="coerce")
    all_missing = [feature for feature in features if development[feature].isna().all()]
    if all_missing:
        raise ValueError(f"Features are entirely missing: {all_missing}")
    return development, features


def outcome(frame: pd.DataFrame) -> np.ndarray:
    return Surv.from_arrays(
        event=frame[EVENT].to_numpy(bool),
        time=frame[TIME].to_numpy(float),
    )


def strata(frame: pd.DataFrame, include_split: bool = True) -> np.ndarray:
    """Stratify on event and, when feasible, original development split."""
    event = frame[EVENT].astype(str)
    if include_split:
        return (frame["split"].astype(str) + "_" + event).to_numpy()
    return event.to_numpy()


def make_folds(frame: pd.DataFrame, n_splits: int, seed: int) -> list[tuple[np.ndarray, np.ndarray]]:
    if n_splits < 2:
        raise ValueError("The number of folds must be at least 2")
    labels = strata(frame)
    counts = pd.Series(labels).value_counts()
    if counts.min() < n_splits:
        labels = strata(frame, include_split=False)
    if pd.Series(labels).value_counts().min() < n_splits:
        raise ValueError("Too few patients in a censoring stratum for the requested folds")
    splitter = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    return list(splitter.split(np.zeros(len(frame)), labels))


def suggest_parameters(trial: optuna.Trial, settings: SearchSettings) -> dict[str, Any]:
    """Search space adapted from the repository's RSF/T-learner arenas."""
    leaf = trial.suggest_int(
        "min_samples_leaf", settings.leaf_low, settings.leaf_high
    )
    split_multiplier = trial.suggest_float("split_multiplier", 2.0, 3.0)
    raw = {
        "n_estimators": trial.suggest_int(
            "n_estimators",
            settings.trees_low,
            settings.trees_high,
            step=settings.trees_step,
        ),
        "max_depth": trial.suggest_categorical(
            "max_depth", list(settings.depth_choices)
        ),
        "min_samples_leaf": leaf,
        "min_samples_split": max(2, int(round(split_multiplier * leaf))),
        "max_features": trial.suggest_float(
            "max_features", settings.max_features_low, settings.max_features_high
        ),
    }
    return raw


def resolved_parameters(params: dict[str, Any], *, random_state: int, n_jobs: int) -> dict[str, Any]:
    """Convert stored Optuna coordinates into RSF constructor parameters."""
    leaf = int(params["min_samples_leaf"])
    return {
        "n_estimators": int(params["n_estimators"]),
        "max_depth": None if params["max_depth"] is None else int(params["max_depth"]),
        "min_samples_leaf": leaf,
        "min_samples_split": max(2, int(round(float(params["split_multiplier"]) * leaf))),
        "max_features": float(params["max_features"]),
        "bootstrap": True,
        "oob_score": False,
        "low_memory": False,
        "n_jobs": int(n_jobs),
        "random_state": int(random_state),
    }


def _fit_imputer_forest(
    x: np.ndarray,
    y: np.ndarray,
    train_index: np.ndarray,
    params: dict[str, Any],
) -> tuple[SimpleImputer, RandomSurvivalForest]:
    imputer = SimpleImputer(strategy="median")
    x_fit = imputer.fit_transform(x[train_index])
    model = RandomSurvivalForest(**params)
    model.fit(x_fit, y[train_index])
    return imputer, model


def harrell_cindex(model: RandomSurvivalForest, x: np.ndarray, y: np.ndarray) -> float:
    risk = np.asarray(model.predict(x), dtype=float)
    return float(concordance_index_censored(y["event"], y["time"], risk)[0])


def optimize_parameters(
    frame: pd.DataFrame,
    features: list[str],
    settings: SearchSettings,
    study_name: str,
) -> tuple[dict[str, Any], optuna.Study]:
    """Tune an RSF with fixed, reproducible internal folds."""
    x = frame[features].to_numpy(float)
    y = outcome(frame)
    folds = make_folds(frame, settings.folds, settings.seed)

    def objective(trial: optuna.Trial) -> float:
        suggested = suggest_parameters(trial, settings)
        scores: list[float] = []
        for fold_number, (fit_index, assess_index) in enumerate(folds):
            params = {
                **suggested,
                "bootstrap": True,
                "oob_score": False,
                "low_memory": False,
                "n_jobs": settings.n_jobs,
                "random_state": settings.seed + 1009 * (fold_number + 1),
            }
            imputer, model = _fit_imputer_forest(x, y, fit_index, params)
            score = harrell_cindex(model, imputer.transform(x[assess_index]), y[assess_index])
            if not np.isfinite(score):
                raise optuna.TrialPruned("Non-finite validation C-index")
            scores.append(score)
            trial.report(float(np.mean(scores)), step=fold_number)
            if trial.should_prune():
                raise optuna.TrialPruned()
        trial.set_user_attr("fold_cindices", [float(value) for value in scores])
        trial.set_user_attr("cindex_sd", float(np.std(scores, ddof=1)))
        return float(np.mean(scores))

    study = optuna.create_study(
        study_name=study_name,
        direction="maximize",
        sampler=TPESampler(seed=settings.seed),
        pruner=MedianPruner(n_startup_trials=max(5, settings.trials // 4)),
    )
    study.optimize(objective, n_trials=settings.trials, n_jobs=1, show_progress_bar=False)
    return dict(study.best_trial.params), study


def integrate_rmst(
    model: RandomSurvivalForest,
    x: np.ndarray,
    tau: float,
    batch_size: int,
) -> np.ndarray:
    """Integrate each RSF stepwise survival curve from zero through ``tau``."""
    if tau <= 0:
        raise ValueError("RMST horizon must be positive")
    times = np.asarray(model.unique_times_, dtype=float)
    internal_index = np.flatnonzero((times > 0) & (times < tau))
    internal_times = times[internal_index]
    bounds = np.concatenate(([0.0], internal_times, [float(tau)]))
    widths = np.diff(bounds)
    output = np.empty(len(x), dtype=float)
    for start in range(0, len(x), batch_size):
        stop = min(start + batch_size, len(x))
        survival = np.asarray(
            model.predict_survival_function(x[start:stop], return_array=True),
            dtype=float,
        )
        # S(t)=1 on [0, first event); after an event-time knot, the survival
        # value at that knot applies until the next knot.
        interval_survival = np.column_stack(
            [np.ones(stop - start), survival[:, internal_index]]
        )
        output[start:stop] = interval_survival @ widths
    return output


def save_study(study: optuna.Study, path: Path) -> None:
    trials = study.trials_dataframe(attrs=("number", "value", "params", "state", "user_attrs"))
    trials.to_csv(path, index=False)


def cross_fitted_obs_predictions(
    obs: pd.DataFrame,
    features: list[str],
    outer_folds: int,
    inner_folds: int,
    outer_trials: int,
    seed: int,
    n_jobs: int,
    tau: float,
    batch_size: int,
    output_dir: Path,
    selection_mode: str,
    global_params: dict[str, Any] | None = None,
    tree_bounds: tuple[int, int, int] = (300, 1000, 100),
) -> tuple[np.ndarray, np.ndarray, list[dict[str, Any]]]:
    """Generate one held-out baseline RMST prediction per OBS patient."""
    x = obs[features].to_numpy(float)
    y = outcome(obs)
    folds = make_folds(obs, outer_folds, seed)
    rmst = np.full(len(obs), np.nan, dtype=float)
    fold_id = np.full(len(obs), -1, dtype=int)
    fold_records: list[dict[str, Any]] = []

    for fold_number, (fit_index, assess_index) in enumerate(folds, start=1):
        fold_seed = seed + 10_000 * fold_number
        if selection_mode == "nested":
            fit_frame = obs.iloc[fit_index].reset_index(drop=True)
            settings = SearchSettings(
                folds=inner_folds,
                trials=outer_trials,
                seed=fold_seed,
                n_jobs=n_jobs,
                trees_low=tree_bounds[0],
                trees_high=tree_bounds[1],
                trees_step=tree_bounds[2],
            )
            best_raw, study = optimize_parameters(
                fit_frame, features, settings, f"obs_outer_fold_{fold_number}"
            )
            save_study(study, output_dir / f"outer_fold_{fold_number}_optuna_trials.csv")
            best_value = float(study.best_value)
        else:
            if global_params is None:
                raise ValueError("global selection mode requires global_params")
            best_raw = dict(global_params)
            best_value = math.nan

        params = resolved_parameters(best_raw, random_state=fold_seed, n_jobs=n_jobs)
        imputer, model = _fit_imputer_forest(x, y, fit_index, params)
        x_assess = imputer.transform(x[assess_index])
        rmst[assess_index] = integrate_rmst(model, x_assess, tau, batch_size)
        fold_id[assess_index] = fold_number
        joblib.dump(
            {"imputer": imputer, "model": model, "features": features, "tau": tau},
            output_dir / f"obs_outer_fold_{fold_number}.joblib",
            compress=3,
        )
        fold_records.append(
            {
                "fold": fold_number,
                "fit_n": int(len(fit_index)),
                "assess_n": int(len(assess_index)),
                "assess_patient_ids": obs.iloc[assess_index][ID].tolist(),
                "optuna_best_cindex": best_value,
                "parameters": params,
            }
        )
        print(
            f"[outer {fold_number}/{outer_folds}] fit={len(fit_index)} "
            f"held_out={len(assess_index)} mean_RMST={np.mean(rmst[assess_index]):.3f}",
            flush=True,
        )

    if np.isnan(rmst).any() or (fold_id < 1).any():
        raise RuntimeError("Cross-fitting failed to predict every OBS patient exactly once")
    return rmst, fold_id, fold_records


def fit_full_obs_and_predict_act(
    obs: pd.DataFrame,
    act: pd.DataFrame,
    features: list[str],
    raw_params: dict[str, Any],
    seed: int,
    n_jobs: int,
    tau: float,
    batch_size: int,
    output_dir: Path,
) -> np.ndarray:
    x_obs = obs[features].to_numpy(float)
    x_act = act[features].to_numpy(float)
    y_obs = outcome(obs)
    all_index = np.arange(len(obs))
    params = resolved_parameters(raw_params, random_state=seed, n_jobs=n_jobs)
    imputer, model = _fit_imputer_forest(x_obs, y_obs, all_index, params)
    act_rmst = integrate_rmst(model, imputer.transform(x_act), tau, batch_size)
    joblib.dump(
        {"imputer": imputer, "model": model, "features": features, "tau": tau},
        output_dir / "full_obs_rsf.joblib",
        compress=3,
    )
    return act_rmst


def _parse_binary_group(values: pd.Series) -> pd.Series:
    normalized = values.astype(str).str.strip().str.lower()
    mapped = normalized.map(
        {
            "true": True,
            "1": True,
            "yes": True,
            "aligned": True,
            "false": False,
            "0": False,
            "no": False,
            "discordant": False,
            "not aligned": False,
            "not_aligned": False,
        }
    )
    if mapped.isna().any():
        bad = sorted(values[mapped.isna()].astype(str).unique().tolist())
        raise ValueError(f"Unrecognized alignment values: {bad}")
    return mapped.astype(bool)


def make_policy_folds(
    frame: pd.DataFrame, n_splits: int, seed: int
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Keep treatment, censoring, and source split balanced across folds."""
    labels = (
        frame["split"].astype(str)
        + "_"
        + frame[TREATMENT].astype(str)
        + "_"
        + frame[EVENT].astype(str)
    )
    if labels.value_counts().min() < n_splits:
        labels = frame[TREATMENT].astype(str) + "_" + frame[EVENT].astype(str)
    if labels.value_counts().min() < n_splits:
        raise ValueError("Too few patients in a treatment/event stratum for policy folds")
    splitter = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    return list(splitter.split(np.zeros(len(frame)), labels))


def policy_search_settings(
    arm: int,
    folds: int,
    trials: int,
    seed: int,
    n_jobs: int,
    tree_bounds: tuple[int, int, int],
) -> SearchSettings:
    """Arm-specific ranges centered on historically strong T-learner regions.

    Historical performance informs only these bounds; every Optuna study and
    every forest is newly fitted from the current development folds.
    """
    if arm == 0:
        depths = POLICY_OBS_DEPTH_CHOICES
        leaf_bounds = POLICY_OBS_LEAF_BOUNDS
    else:
        depths = POLICY_ACT_DEPTH_CHOICES
        leaf_bounds = POLICY_ACT_LEAF_BOUNDS
    return SearchSettings(
        folds=folds,
        trials=trials,
        seed=seed,
        n_jobs=n_jobs,
        trees_low=tree_bounds[0],
        trees_high=tree_bounds[1],
        trees_step=tree_bounds[2],
        leaf_low=leaf_bounds[0],
        leaf_high=leaf_bounds[1],
        depth_choices=depths,
        max_features_low=POLICY_MAX_FEATURES_BOUNDS[0],
        max_features_high=POLICY_MAX_FEATURES_BOUNDS[1],
    )


def generate_retrained_alignment(
    development: pd.DataFrame,
    features: list[str],
    output_dir: Path,
    *,
    outer_folds: int,
    inner_folds: int,
    trials: int,
    seed: int,
    n_jobs: int,
    tau: float,
    batch_size: int,
    tree_bounds: tuple[int, int, int],
) -> Path:
    """Train a new nested-cross-fitted RSF T-learner for policy alignment."""
    folds = make_policy_folds(development, outer_folds, seed)
    rmst0 = np.full(len(development), np.nan, dtype=float)
    rmst1 = np.full(len(development), np.nan, dtype=float)
    audit_rows: list[dict[str, Any]] = []

    print(
        f"[alignment] training a new OOF T-learner: folds={outer_folds} "
        f"inner_folds={inner_folds} trials/arm/fold={trials}",
        flush=True,
    )
    for fold_number, (fit_index, assess_index) in enumerate(folds, start=1):
        fit = development.iloc[fit_index].reset_index(drop=True)
        assess = development.iloc[assess_index].reset_index(drop=True)
        fold_record: dict[str, Any] = {
            "fold": fold_number,
            "fit_n": int(len(fit)),
            "assess_n": int(len(assess)),
            "arms": {},
        }
        for arm, label in ((0, "observation"), (1, "act")):
            arm_fit = fit.loc[fit[TREATMENT] == arm].reset_index(drop=True)
            arm_seed = seed + 100_000 * fold_number + 10_000 * arm
            settings = policy_search_settings(
                arm,
                inner_folds,
                trials,
                arm_seed,
                n_jobs,
                tree_bounds,
            )
            raw_params, study = optimize_parameters(
                arm_fit,
                features,
                settings,
                f"policy_fold_{fold_number}_{label}",
            )
            save_study(
                study,
                output_dir / f"policy_fold_{fold_number}_{label}_optuna_trials.csv",
            )
            params = resolved_parameters(
                raw_params, random_state=arm_seed + 5_000_000, n_jobs=n_jobs
            )
            x_fit = arm_fit[features].to_numpy(float)
            y_fit = outcome(arm_fit)
            imputer, model = _fit_imputer_forest(
                x_fit, y_fit, np.arange(len(arm_fit)), params
            )
            predicted = integrate_rmst(
                model,
                imputer.transform(assess[features].to_numpy(float)),
                tau,
                batch_size,
            )
            if arm == 0:
                rmst0[assess_index] = predicted
            else:
                rmst1[assess_index] = predicted
            joblib.dump(
                {"imputer": imputer, "model": model, "features": features, "tau": tau},
                output_dir / f"policy_fold_{fold_number}_{label}.joblib",
                compress=3,
            )
            fold_record["arms"][label] = {
                "fit_n": int(len(arm_fit)),
                "events": int(arm_fit[EVENT].sum()),
                "optuna_best_cindex": float(study.best_value),
                "parameters": params,
            }
        audit_rows.append(fold_record)
        print(
            f"[alignment fold {fold_number}/{outer_folds}] assessed={len(assess_index)}",
            flush=True,
        )

    if np.isnan(rmst0).any() or np.isnan(rmst1).any():
        raise RuntimeError("Policy cross-fitting failed to predict every development patient")
    benefit = rmst1 - rmst0
    recommendation = (benefit > 1e-6).astype(int)
    actual = development[TREATMENT].to_numpy(int)
    alignment = actual == recommendation
    policy_output = pd.DataFrame(
        {
            ID: development[ID].to_numpy(str),
            "actual_treatment": np.where(actual == 1, "ACT", "OBS"),
            "recommendation": np.where(recommendation == 1, "ACT", "OBS"),
            "alignment": np.where(alignment, "aligned", "discordant"),
            "predicted_obs_rmst_policy_model": rmst0,
            "predicted_act_rmst_policy_model": rmst1,
            "predicted_benefit_months": benefit,
        }
    )
    path = output_dir / "retrained_policy_oof_predictions.csv"
    policy_output.to_csv(path, index=False)
    (output_dir / "retrained_policy_audit.json").write_text(
        json.dumps(
            {
                "source": "newly fitted clinical RSF T-learner",
                "historical_use": "Prior performance used only to set Optuna bounds",
                "outer_folds": outer_folds,
                "inner_folds": inner_folds,
                "trials_per_arm_per_fold": trials,
                "folds_audit": audit_rows,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return path


def attach_alignment(
    predictions: pd.DataFrame,
    alignment_path: Path,
    alignment_id_column: str,
    alignment_column: str,
    recommendation_column: str,
) -> pd.DataFrame:
    groups = pd.read_csv(alignment_path)
    if alignment_id_column not in groups:
        raise ValueError(
            f"Alignment file has no identifier column {alignment_id_column!r}: {alignment_path}"
        )
    groups = groups.rename(columns={alignment_id_column: ID})
    groups[ID] = groups[ID].astype(str)
    if groups[ID].duplicated().any():
        raise ValueError("Alignment file contains duplicate patient identifiers")

    if alignment_column in groups:
        groups["is_aligned"] = _parse_binary_group(groups[alignment_column])
        keep_columns = [ID, "is_aligned"]
        if recommendation_column in groups:
            groups["recommendation"] = _map_treatment(groups[recommendation_column])
            keep_columns.append("recommendation")
        keep = groups[keep_columns]
    elif recommendation_column in groups:
        groups["recommendation"] = _map_treatment(groups[recommendation_column])
        keep = groups[[ID, "recommendation"]]
    else:
        raise ValueError(
            f"Alignment file must contain {alignment_column!r} or {recommendation_column!r}"
        )

    merged = predictions.merge(keep, on=ID, how="left", validate="one_to_one")
    group_value_column = "is_aligned" if "is_aligned" in keep else "recommendation"
    if merged[group_value_column].isna().any():
        missing = merged.loc[merged[group_value_column].isna(), ID].tolist()
        raise ValueError(
            f"Alignment file is missing {len(missing)} development patients; first: {missing[:5]}"
        )
    if "is_aligned" not in merged:
        merged["recommendation"] = merged["recommendation"].astype(int)
        merged["is_aligned"] = merged[TREATMENT].astype(int) == merged["recommendation"]
    elif "recommendation" in merged:
        derived = merged[TREATMENT].astype(int) == merged["recommendation"].astype(int)
        if not np.array_equal(derived.to_numpy(bool), merged["is_aligned"].to_numpy(bool)):
            raise ValueError("Alignment and recommendation columns disagree with actual treatment")
    merged["alignment_group"] = np.where(merged["is_aligned"], "Aligned", "Discordant")
    return merged


def pooled_smd(aligned: np.ndarray, discordant: np.ndarray) -> float:
    n_a, n_d = len(aligned), len(discordant)
    if n_a < 2 or n_d < 2:
        return math.nan
    var_a = float(np.var(aligned, ddof=1))
    var_d = float(np.var(discordant, ddof=1))
    pooled = math.sqrt(((n_a - 1) * var_a + (n_d - 1) * var_d) / (n_a + n_d - 2))
    if pooled == 0:
        return 0.0 if np.mean(aligned) == np.mean(discordant) else math.copysign(math.inf, np.mean(aligned) - np.mean(discordant))
    return float((np.mean(aligned) - np.mean(discordant)) / pooled)


def summarize_baseline_prognosis(frame: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, Any]]:
    values: dict[str, np.ndarray] = {}
    details: dict[str, Any] = {}
    for group in ("Aligned", "Discordant"):
        group_values = frame.loc[
            frame["alignment_group"] == group, "predicted_obs_rmst"
        ].to_numpy(float)
        if len(group_values) == 0:
            raise ValueError(f"The table has no {group.lower()} patients")
        values[group] = group_values
        q1, q3 = np.percentile(group_values, [25, 75])
        details[group] = {
            "n": int(len(group_values)),
            "mean": float(np.mean(group_values)),
            "sd": float(np.std(group_values, ddof=1)) if len(group_values) > 1 else math.nan,
            "median": float(np.median(group_values)),
            "q1": float(q1),
            "q3": float(q3),
            "iqr": float(q3 - q1),
        }
    smd = pooled_smd(values["Aligned"], values["Discordant"])
    details["smd_aligned_minus_discordant"] = smd
    table = pd.DataFrame(
        {
            "Baseline prognosis": [
                "N",
                "Mean predicted OBS RMST (months)",
                "SD (months)",
                "Median (months)",
                "IQR (months)",
                "SMD (aligned - discordant) / pooled SD",
            ],
            "Aligned": pd.Series([
                details["Aligned"]["n"],
                details["Aligned"]["mean"],
                details["Aligned"]["sd"],
                details["Aligned"]["median"],
                details["Aligned"]["iqr"],
                smd,
            ], dtype=object),
            "Discordant": pd.Series([
                details["Discordant"]["n"],
                details["Discordant"]["mean"],
                details["Discordant"]["sd"],
                details["Discordant"]["median"],
                details["Discordant"]["iqr"],
                np.nan,
            ], dtype=object),
        }
    )
    return table, details


def save_table_figure(table: pd.DataFrame, path: Path) -> None:
    display = table.astype(object).copy()
    for row in range(len(display)):
        for column in ("Aligned", "Discordant"):
            value = display.loc[row, column]
            if pd.isna(value):
                display.loc[row, column] = ""
            elif isinstance(value, str):
                display.loc[row, column] = value
            elif display.loc[row, "Baseline prognosis"] == "N":
                display.loc[row, column] = f"{int(value)}"
            elif display.loc[row, "Baseline prognosis"].startswith("SMD"):
                display.loc[row, column] = f"{float(value):.3f}"
            else:
                display.loc[row, column] = f"{float(value):.1f}"
    height = 1.2 + 0.55 * len(display)
    fig, ax = plt.subplots(figsize=(11.5, height))
    ax.axis("off")
    artist = ax.table(
        cellText=display.values,
        colLabels=display.columns,
        cellLoc="right",
        colLoc="center",
        colWidths=[0.62, 0.19, 0.19],
        loc="center",
    )
    artist.auto_set_font_size(False)
    artist.set_fontsize(12)
    artist.scale(1, 1.55)
    for (row, column), cell in artist.get_celld().items():
        cell.set_edgecolor("#9fc5e8")
        if row == 0:
            cell.set_text_props(weight="bold")
            cell.set_facecolor("#eaf3f8")
        elif column == 0:
            cell.set_text_props(weight="bold", ha="left")
    fig.tight_layout()
    fig.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    """Run the workflow using the user-editable constants at the top."""
    if OUTER_TRIALS < 1 or FINAL_TRIALS < 1 or POLICY_TRIALS < 1:
        raise ValueError("Optuna trial counts must be positive")
    if BATCH_SIZE < 1:
        raise ValueError("Batch size must be positive")
    if MAX_GENES is not None and MAX_GENES < 1:
        raise ValueError("MAX_GENES must be positive")
    if TABLE_SPLIT not in {"all", "train", "validation"}:
        raise ValueError("TABLE_SPLIT must be 'all', 'train', or 'validation'")
    if SELECTION_MODE not in {"nested", "global"}:
        raise ValueError("SELECTION_MODE must be 'nested' or 'global'")

    optuna.logging.set_verbosity(optuna.logging.WARNING)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    development, features = load_development(
        TRAIN_CSV,
        VALIDATION_CSV,
        GENE_LIST,
        GENE_COLUMN,
        MAX_GENES,
    )
    obs = development.loc[development[TREATMENT] == 0].reset_index(drop=True)
    act = development.loc[development[TREATMENT] == 1].reset_index(drop=True)
    if len(obs) < OUTER_FOLDS or len(act) == 0:
        raise ValueError("The development data do not support the requested OBS/ACT workflow")
    print(
        f"[data] development={len(development)} OBS={len(obs)} ACT={len(act)} "
        f"features={len(features)}",
        flush=True,
    )

    if SMOKE:
        outer_folds = min(SMOKE_FOLDS, OUTER_FOLDS)
        inner_folds = min(SMOKE_FOLDS, INNER_FOLDS)
        outer_trials = min(SMOKE_TRIALS, OUTER_TRIALS)
        final_trials = min(SMOKE_TRIALS, FINAL_TRIALS)
        policy_trials = min(SMOKE_TRIALS, POLICY_TRIALS)
        tree_bounds = SMOKE_TREE_BOUNDS
    else:
        outer_folds = OUTER_FOLDS
        inner_folds = INNER_FOLDS
        outer_trials = OUTER_TRIALS
        final_trials = FINAL_TRIALS
        policy_trials = POLICY_TRIALS
        tree_bounds = (TREES_LOW, TREES_HIGH, TREES_STEP)

    alignment_path = ALIGNMENT_FILE
    alignment_source = "user_file"
    if alignment_path is None:
        alignment_path = generate_retrained_alignment(
            development,
            features,
            OUTPUT_DIR,
            outer_folds=outer_folds,
            inner_folds=inner_folds,
            trials=policy_trials,
            seed=SEED + 2_700_000,
            n_jobs=N_JOBS,
            tau=TAU,
            batch_size=BATCH_SIZE,
            tree_bounds=tree_bounds,
        )
        alignment_source = "new_cross_fitted_tlearner"

    # The final all-OBS study is separate from the nested studies used for
    # honest OBS predictions.  Its winner is used for the full-OBS ACT model.
    final_settings = SearchSettings(
        folds=outer_folds,
        trials=final_trials,
        seed=SEED + 900_000,
        n_jobs=N_JOBS,
        trees_low=tree_bounds[0],
        trees_high=tree_bounds[1],
        trees_step=tree_bounds[2],
    )
    final_raw, final_study = optimize_parameters(
        obs, features, final_settings, "full_obs_hyperparameter_search"
    )
    save_study(final_study, OUTPUT_DIR / "full_obs_optuna_trials.csv")
    print(f"[Optuna full OBS] best C-index={final_study.best_value:.4f} params={final_raw}")

    obs_rmst, obs_fold, fold_records = cross_fitted_obs_predictions(
        obs=obs,
        features=features,
        outer_folds=outer_folds,
        inner_folds=inner_folds,
        outer_trials=outer_trials,
        seed=SEED,
        n_jobs=N_JOBS,
        tau=TAU,
        batch_size=BATCH_SIZE,
        output_dir=OUTPUT_DIR,
        selection_mode=SELECTION_MODE,
        global_params=final_raw,
        tree_bounds=tree_bounds,
    )
    act_rmst = fit_full_obs_and_predict_act(
        obs=obs,
        act=act,
        features=features,
        raw_params=final_raw,
        seed=SEED + 1_800_000,
        n_jobs=N_JOBS,
        tau=TAU,
        batch_size=BATCH_SIZE,
        output_dir=OUTPUT_DIR,
    )

    obs_predictions = obs[[ID, "split", TREATMENT, TIME, EVENT]].copy()
    obs_predictions["oof_fold"] = obs_fold
    obs_predictions["prediction_source"] = "held_out_obs_fold"
    obs_predictions["predicted_obs_rmst"] = obs_rmst
    act_predictions = act[[ID, "split", TREATMENT, TIME, EVENT]].copy()
    act_predictions["oof_fold"] = pd.array([pd.NA] * len(act), dtype="Int64")
    act_predictions["prediction_source"] = "full_obs_model"
    act_predictions["predicted_obs_rmst"] = act_rmst
    predictions = pd.concat([obs_predictions, act_predictions], ignore_index=True)
    predictions = attach_alignment(
        predictions,
        alignment_path,
        ALIGNMENT_ID_COLUMN,
        ALIGNMENT_COLUMN,
        RECOMMENDATION_COLUMN,
    )
    predictions[TREATMENT] = predictions[TREATMENT].map({0: "OBS", 1: "ACT"})
    if "recommendation" in predictions:
        predictions["recommendation"] = predictions["recommendation"].map(
            {0: "OBS", 1: "ACT"}
        )
    predictions.to_csv(OUTPUT_DIR / "patient_predictions.csv", index=False)

    table_frame = predictions
    if TABLE_SPLIT != "all":
        table_frame = table_frame.loc[table_frame["split"] == TABLE_SPLIT].copy()
    table, table_details = summarize_baseline_prognosis(table_frame)
    table.to_csv(OUTPUT_DIR / "baseline_prognosis_table.csv", index=False)
    save_table_figure(table, OUTPUT_DIR / "baseline_prognosis_table.png")

    manifest = {
        "estimator": "OBS-only RandomSurvivalForest predicted 60-month RMST",
        "tau_months": float(TAU),
        "selection_mode": SELECTION_MODE,
        "contamination_control": (
            "Nested outer cross-fitting: each OBS patient's outcome was excluded from both "
            "its fold-specific Optuna search and fitted model."
            if SELECTION_MODE == "nested"
            else "Each OBS patient's outcome was excluded from its fitted fold model, but was "
            "used by the all-OBS Optuna hyperparameter search."
        ),
        "act_prediction": "Full OBS-only model fit to pooled train+validation OBS patients",
        "n_development": int(len(development)),
        "n_obs": int(len(obs)),
        "n_act": int(len(act)),
        "features": features,
        "external_gene_list": str(GENE_LIST.resolve()) if GENE_LIST else None,
        "gene_list_requirement": (
            "Any external gene list must be prespecified or selected without using each "
            "assessed patient's outcome; downstream cross-fitting cannot repair upstream "
            "feature-selection leakage."
        ),
        "outer_folds": int(outer_folds),
        "inner_folds": int(inner_folds),
        "outer_trials": int(outer_trials),
        "final_trials": int(final_trials),
        "policy_trials_per_arm_per_fold": int(policy_trials),
        "optuna_search_space_basis": (
            "Bounds informed by prior repository T-learner performance; all studies, "
            "hyperparameters, and models in this run were fitted from scratch."
        ),
        "smoke": bool(SMOKE),
        "full_obs_optuna_best_cindex": float(final_study.best_value),
        "full_obs_optuna_best_trial": int(final_study.best_trial.number),
        "full_obs_parameters": resolved_parameters(
            final_raw, random_state=SEED + 1_800_000, n_jobs=N_JOBS
        ),
        "outer_fold_models": fold_records,
        "alignment_source": alignment_source,
        "alignment_file": str(alignment_path.resolve()),
        "table_split": TABLE_SPLIT,
        "baseline_prognosis": table_details,
        "smd_definition": "(mean aligned - mean discordant) / sample-size pooled SD",
    }
    (OUTPUT_DIR / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print("\n" + table.to_string(index=False, na_rep=""))
    print(f"\n[done] outputs written to {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2)
